version: '3'

services:
  mzk-krom-app:
    image: michaeltran262/mzk-krom-app:1.1.9
    container_name: mzk-krom-app
    expose:
      - 5000
    volumes:
      - ./data:/mnt/data
      - ./logs:/logs
      - ./config.py:/krom_app/config.py
      - /mnt/MZK:/mnt/MZK
    env_file:
      - .env
    command: "gunicorn -b 0.0.0.0:5000 --chdir /krom_app --worker-tmp-dir /dev/shm --workers=1 -k eventlet --log-level info krom_app:flask_app"
    links:
      - mzk-postgres
    restart: always
    depends_on:
      - mzk-postgres
      - mzk-redis
      - mzk-worker
    
  mzk-worker:
    image: michaeltran262/mzk-krom-app:1.1.9
    container_name: mzk-worker
    volumes:
      - ./data:/mnt/data
      - ./logs:/logs
      - ./config.py:/krom_app/config.py
      - /mnt/MZK:/mnt/MZK
    command: "celery -A krom_app:celery_app worker -B --loglevel=debug"
    env_file:
      - .env
    links:
      - mzk-postgres
    restart: always
    
  mzk-flower:
    image: michaeltran262/mzk-krom-app:1.1.9
    container_name: mzk-flower
    volumes:
      - ./data:/mnt/data
      - ./logs:/logs
      - ./config.py:/krom_app/config.py
      - ./flower:/flower
      - /mnt/MZK:/mnt/MZK
    command: "celery -A krom_app:celery_app flower --persistent=True --db=/flower/flower.db --max_tasks=1000"
    env_file:
      - .env
    depends_on:
      - mzk-worker
    restart: always
    ports:
      - "5555:5555"
    expose:
      - 5555

  mzk-postgres:
    image: postgres:15
    container_name: mzk-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mzkdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  mzk-redis:
    image: redis:6-alpine
    container_name: mzk-redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    depends_on:
      - mzk-postgres

  mzk-nginx:
    image: nginx:1.24-alpine
    container_name: mzk-nginx
    volumes:
      - ./nginx/sites-enabled.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    links:
      - mzk-krom-app

volumes:
  cache:
    driver: local